import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';

// shadowSaveToDrive — saves a Shadow agent method's architecture and strategy
// playbook to a dedicated "Vision Cortex Shadow" folder in Google Drive as a
// Google Doc. Auto-creates the folder if it doesn't exist.

export default async function(req) {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const body = await req.json().catch(() => ({}));
    const queueId = body.queue_id;

    if (!queueId) return Response.json({ error: 'queue_id required' }, { status: 400 });

    // Get the BuildQueue entry
    const queueItem = await base44.entities.BuildQueue.get(queueId).catch(() => null);
    if (!queueItem) return Response.json({ error: 'Build queue entry not found' }, { status: 404 });

    // Get Google Drive connection
    const { accessToken } = await base44.asServiceRole.connectors.getConnection('googledrive');
    const authHeader = { 'Authorization': `Bearer ${accessToken}` };

    const FOLDER_NAME = 'Vision Cortex Shadow';

    // Find or create the folder
    const searchRes = await fetch(
      `https://www.googleapis.com/drive/v3/files?q=name='${FOLDER_NAME}' and mimeType='application/vnd.google-apps.folder' and trashed=false`,
      { headers: authHeader }
    );
    const searchData = await searchRes.json();
    let folderId = searchData.files?.[0]?.id;

    if (!folderId) {
      const createFolderRes = await fetch('https://www.googleapis.com/drive/v3/files', {
        method: 'POST',
        headers: { ...authHeader, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: FOLDER_NAME,
          mimeType: 'application/vnd.google-apps.folder',
        }),
      });
      const folderData = await createFolderRes.json();
      folderId = folderData.id;
    }

    // Build the document content from the BuildQueue entry + related intel
    const businessName = queueItem.business_name || queueItem.title;
    const docTitle = `${businessName} — Strategy Playbook`;

    // Pull related IntelFeed for this method
    const intel = await base44.entities.IntelFeed.filter(
      { source: 'Shadow Money Hunt' },
      '-created_date',
      10
    ).catch(() => []);
    const relatedIntel = intel.find((i) =>
      i.headline?.toLowerCase().includes((businessName || '').toLowerCase().slice(0, 15))
    );

    const content = [
      `VISION CORTEX — SHADOW STRATEGY PLAYBOOK`,
      `===============================================`,
      ``,
      `Project: ${businessName}`,
      `Industry: ${queueItem.industry || 'N/A'}`,
      `Product Type: ${queueItem.product_type || 'marketing_site'}`,
      `Queue ID: ${queueItem.id}`,
      `Generated: ${new Date().toISOString()}`,
      ``,
      `-----------------------------------------------`,
      `EXECUTIVE SUMMARY`,
      `-----------------------------------------------`,
      relatedIntel?.summary || 'See architecture below for full details.',
      ``,
      `-----------------------------------------------`,
      `BUILD QUEUE STATUS`,
      `-----------------------------------------------`,
      `Stage: ${queueItem.stage}`,
      `Status: ${queueItem.status}`,
      `Priority: ${queueItem.priority}`,
      `Assigned Agent: ${queueItem.assigned_agent || 'Shadow'}`,
      `Auto-Advance: ${queueItem.auto_advance ? 'Enabled' : 'Disabled'}`,
      ``,
      `-----------------------------------------------`,
      `BUILD LOG`,
      `-----------------------------------------------`,
      (queueItem.logs || []).join('\n') || 'No build logs yet.',
      ``,
      `-----------------------------------------------`,
      `NOTES`,
      `-----------------------------------------------`,
      queueItem.notes || 'No additional notes.',
      ``,
      `===============================================`,
      `Generated by Vision Cortex Shadow Agent`,
    ].join('\n');

    // Create the Google Doc via multipart upload
    const boundary = '-------vc_boundary_' + Math.random().toString(16).slice(2);
    const multipartBody = [
      '--' + boundary,
      'Content-Type: application/json; charset=UTF-8',
      '',
      JSON.stringify({
        name: docTitle,
        parents: [folderId],
        mimeType: 'application/vnd.google-apps.document',
      }),
      '--' + boundary,
      'Content-Type: text/plain',
      '',
      content,
      '--' + boundary + '--',
    ].join('\r\n');

    const uploadRes = await fetch(
      'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,webViewLink,name',
      {
        method: 'POST',
        headers: {
          ...authHeader,
          'Content-Type': `multipart/related; boundary="${boundary}"`,
        },
        body: multipartBody,
      }
    );

    if (!uploadRes.ok) {
      const err = await uploadRes.json().catch(() => ({}));
      return Response.json({ error: `Drive upload failed: ${err.error?.message || uploadRes.statusText}` }, { status: 500 });
    }

    const fileData = await uploadRes.json();

    await base44.entities.AgentLog.create({
      agent_name: 'Shadow',
      level: 'success',
      category: 'drive',
      message: `Saved "${docTitle}" to Google Drive folder "${FOLDER_NAME}".`,
      detail: fileData.webViewLink,
    });

    return Response.json({
      saved: true,
      file_id: fileData.id,
      file_name: fileData.name,
      web_view_link: fileData.webViewLink,
      folder: FOLDER_NAME,
    });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
}