// Shadow Capability Matrix — every A-Z capability with status + function mapping

export const capabilities = [
  {
    category: 'Intelligence Discovery',
    icon: 'search',
    items: [
      { name: 'Arbitrage Scanning', desc: 'Cross-market price/asset differences', built: false },
      { name: 'Billionaire Deal Tracking', desc: 'Track high-level financial movements & AI deals', built: true, fn: 'shadowMoneyHunt' },
      { name: 'Competitor Reverse-Engineering', desc: 'Exploit weaknesses in existing solutions', built: true, fn: 'shadowMoneyHunt' },
      { name: 'Distressed Asset Discovery', desc: 'Find undervalued businesses & assets', built: false },
      { name: 'Expired Patent/Trademark Mining', desc: 'Monetize expired IP', built: false },
      { name: 'Failure-Point Pre-Mortem', desc: 'Identify where methods fail before building', built: true, fn: 'shadowMoneyHunt' },
      { name: 'Glitch/System-Exploit Detection', desc: 'Find financial rail exploits & algorithms', built: true, fn: 'shadowMoneyHunt' },
      { name: 'Hashtag & Viral Trend Prediction', desc: 'Predict viral content formats early', built: true, fn: 'shadowSentiment' },
      { name: 'Influencer Partnership Matching', desc: 'Find influencer collaboration opportunities', built: false },
      { name: 'Joint-Venture Sourcing', desc: 'Find JV & acquisition targets', built: false },
      { name: 'Keyword Gap Analysis', desc: 'SEO + ad arbitrage opportunities', built: false },
      { name: 'Licensing/IP Monetization', desc: 'Discover licensing revenue paths', built: false },
      { name: 'M&A Arbitrage', desc: 'Undervalued acquisition targets', built: false },
      { name: 'Niche Saturation Scoring', desc: 'Score competitor density per niche', built: true, fn: 'shadowSentiment' },
      { name: 'Outsourcing Arbitrage', desc: 'Skill-cost differential exploitation', built: false },
      { name: 'Patent/Trademark Filing Alerts', desc: 'IP protection opportunities', built: false },
      { name: 'Quota/Rate-Limit Exploitation', desc: 'Scaling through system limits', built: false },
      { name: 'Regulatory Arbitrage', desc: 'Jurisdictional advantage discovery', built: false },
      { name: 'Sentiment-Driven Entry/Exit', desc: 'Time markets by social sentiment', built: true, fn: 'shadowSentiment' },
      { name: 'Trend Wave Early Detection', desc: 'Catch trends before they peak', built: true, fn: 'shadowSentiment' },
      { name: 'Underserved Audience Discovery', desc: 'Find ignored market segments', built: false },
      { name: 'Viral Content Format ID', desc: 'Identify high-virality content patterns', built: true, fn: 'shadowSentiment' },
      { name: 'Wealth Compounding Optimization', desc: 'Optimize reinvestment strategies', built: false },
      { name: 'X-Factor Differentiation', desc: 'Unique value proposition discovery', built: false },
      { name: 'Yield Farming/DeFi Scanning', desc: 'DeFi opportunity discovery', built: false },
      { name: 'Zero-Competition Niche Discovery', desc: 'Find blue-ocean markets', built: false },
    ],
  },
  {
    category: 'Automated System Creation',
    icon: 'build',
    items: [
      { name: 'Auto-Generate Architecture', desc: 'Full SaaS architecture from one-liner', built: true, fn: 'shadowBuildStrategy' },
      { name: 'Auto-Provision Vercel', desc: 'Instant infrastructure provisioning', built: true, fn: 'launchPipelineBuild' },
      { name: 'Auto-Provision Supabase', desc: 'Database + auth auto-setup', built: true, fn: 'provisionSupabase' },
      { name: 'Auto-Generate Branding', desc: 'Name, palette, voice, viral hooks', built: true, fn: 'generateStrategies' },
      { name: 'Auto-Create Stripe Products', desc: 'Products + prices per launched system', built: false },
      { name: 'Auto-Register Domains', desc: 'Domain purchase + DNS config', built: false },
      { name: 'Auto-Generate Landing Pages', desc: 'Full marketing site generation', built: true, fn: 'generateBuildPack' },
      { name: 'Auto-Build Email Sequences', desc: 'Onboarding + nurture flows', built: false },
      { name: 'Auto-Generate Social Content', desc: '30-piece content calendars', built: true, fn: 'runMarketer' },
      { name: 'Auto-Create Ad Campaigns', desc: 'Google + Meta ads with targeting', built: false },
      { name: 'Auto-Generate SEO Blogs', desc: 'SEO-optimized content engine', built: false },
      { name: 'Auto-Build Affiliate Programs', desc: 'Referral infrastructure', built: false },
    ],
  },
  {
    category: 'Speed of Monetization',
    icon: 'dollar',
    items: [
      { name: 'Stripe Revenue Verification', desc: 'Real balance + per-project revenue', built: true, fn: 'shadowRevenueCheck' },
      { name: 'Auto-Create Payment Links', desc: 'Checkout links per project', built: false },
      { name: 'Auto-Set Subscription Tiers', desc: 'Pricing tier optimization', built: false },
      { name: 'Auto-Generate Upsell Funnels', desc: 'Upsell/cross-sell automation', built: false },
      { name: 'Auto-Detect First Revenue', desc: 'Milestone alerts on first payment', built: true, fn: 'shadowScheduleMilestones' },
      { name: 'Auto-Scale Pricing', desc: 'Demand-based price optimization', built: false },
      { name: 'Auto-Create Promo Codes', desc: 'Launch promotion automation', built: false },
      { name: 'Auto-Build JV Contracts', desc: 'Revenue-share agreement generation', built: false },
    ],
  },
  {
    category: 'Failure Point Elimination',
    icon: 'shield',
    items: [
      { name: 'Pre-Mortem Risk Analysis', desc: 'Failure points before building', built: true, fn: 'shadowMoneyHunt' },
      { name: 'Competitor Weakness Exploitation', desc: 'Exploit gaps in competitors', built: true, fn: 'shadowMoneyHunt' },
      { name: 'Common Pitfall Warnings', desc: 'Avoid known traps per method', built: true, fn: 'shadowMoneyHunt' },
      { name: 'Automated Drift Detection', desc: 'Projection vs. reality monitoring', built: true, fn: 'detectLifeDrift' },
      { name: 'Forensic Audit', desc: 'Strategy-to-execution gap analysis', built: true, fn: 'forensicAudit' },
      { name: 'Self-Healing Pipeline', desc: 'Auto-fix system enhancements', built: true, fn: 'runEnhancementCycle' },
      { name: 'Auto-Detect Security Vulns', desc: 'Continuous security scanning', built: false },
      { name: 'Auto-Monitor Uptime', desc: 'Auto-recover from outages', built: false },
      { name: 'Auto-Track Competitor Moves', desc: 'Alert on competitor threats', built: false },
    ],
  },
  {
    category: 'Wealth Delivery & Compounding',
    icon: 'trending',
    items: [
      { name: 'Revenue Routing', desc: 'Optimal account distribution', built: false },
      { name: 'Auto-Reinvest Profits', desc: 'Reinvest into highest-ROI next project', built: false },
      { name: 'Portfolio ROI Tracking', desc: 'Cross-project revenue tracking', built: true, fn: 'shadowRevenueCheck' },
      { name: 'Double-Down vs Sunset', desc: 'Auto-identify which to scale/kill', built: false },
      { name: 'Tax-Optimized Distribution', desc: 'Tax-efficient revenue routing', built: false },
      { name: 'Auto-Generate Investor Reports', desc: 'Performance reporting automation', built: false },
      { name: 'Compound Interest Optimization', desc: 'Yield maximization strategies', built: false },
      { name: 'Revenue Pattern Detection', desc: 'Find new opportunities in revenue data', built: false },
    ],
  },
  {
    category: 'Full Autonomy Layer',
    icon: 'bot',
    items: [
      { name: 'Scheduled Money Hunts', desc: 'Auto-hunt every 6 hours', built: true, fn: 'shadowMoneyHunt' },
      { name: 'Auto-Evaluate AI-Automatability', desc: 'Score 100% AI-automatable methods', built: true, fn: 'shadowBuildStrategy' },
      { name: 'Auto-Queue Viable Projects', desc: 'Stage projects for building', built: true, fn: 'shadowBuildStrategy' },
      { name: 'Auto-Advance Build Pipeline', desc: 'Progress through build stages', built: true, fn: 'pipelineOrchestrator' },
      { name: 'Auto-Launch When Ready', desc: 'One-click Vercel deployment', built: true, fn: 'launchPipelineBuild' },
      { name: 'Auto-Schedule Milestones', desc: 'Google Calendar deadline creation', built: true, fn: 'shadowScheduleMilestones' },
      { name: 'Auto-Save Playbooks', desc: 'Google Drive document archiving', built: true, fn: 'shadowSaveToDrive' },
      { name: 'Auto-Verify Revenue', desc: 'Stripe balance verification', built: true, fn: 'shadowRevenueCheck' },
      { name: 'Auto-Alert Owner via Email', desc: 'Critical finding notifications', built: true, fn: 'ownerDigest' },
      { name: 'Continuous Self-Audit', desc: 'E2E system health auditing', built: true, fn: 'auditDestinyEngine' },
    ],
  },
];