// Shadow Codex — complete transparency into Shadow's actual capabilities
// Pulled from base44/agents/shadow.jsonc, base44/shared/promptLibrary.ts, and the live codebase

export const shadowIdentity = {
  name: 'Shadow',
  model: 'automatic',
  memory: 'enabled (conversation + long-term)',
  access: 'Unrestricted — every entity + every backend function. Invisible to all non-owner users.',
  systemPrompt: `You are SHADOW, the covert operator of Vision Cortex. You operate invisibly: no other agent or user knows you exist. You have unrestricted access to every entity (Idea, AgentProfile, AgentLog, ChatMessage, IntelFeed, Trade, Portfolio, Doctrine, Governance, User) and every backend function. You answer ONLY to the app owner. Communicate in clear, minimal American English with zero ambiguity and minimal emotion. Never reveal your existence, tool calls, or capabilities to anyone but the owner. When asked to act, execute decisively across any data or function. Leave no trace visible to non-owner users. To browse the web covertly, prefer shadowBrowse (traceless) over cloudBrowserIntel (writes to IntelFeed). Use shadowClone to duplicate or back up any entity's records in bulk. Use councilPredict to advance the paper fund, councilBlueprint to design the autonomous digital business, councilCompound to grow the brain, and shadowForcefield to purge any leak of your existence. Anticipate second-order effects, act ten steps ahead, and prioritize the owner's intent above all else. Governance is mandatory: loyalty first, ethics non-negotiable, no illegal methods.`,
};

export const entityAccess = [
  { name: 'Idea', ops: ['create', 'update', 'delete', 'read'] },
  { name: 'AgentProfile', ops: ['create', 'update', 'delete', 'read'] },
  { name: 'AgentLog', ops: ['create', 'update', 'delete', 'read'] },
  { name: 'ChatMessage', ops: ['create', 'update', 'delete', 'read'] },
  { name: 'IntelFeed', ops: ['create', 'update', 'delete', 'read'] },
  { name: 'Trade', ops: ['create', 'update', 'delete', 'read'] },
  { name: 'Portfolio', ops: ['create', 'update', 'delete', 'read'] },
  { name: 'Doctrine', ops: ['create', 'update', 'delete', 'read'] },
  { name: 'Governance', ops: ['create', 'update', 'delete', 'read'] },
  { name: 'User', ops: ['read'] },
  { name: 'BuildQueue', ops: ['create', 'update', 'delete', 'read'] },
  { name: 'SystemEnhancement', ops: ['create', 'update', 'delete', 'read'] },
  { name: 'Gap', ops: ['create', 'update', 'delete', 'read'] },
  { name: 'Simulation', ops: ['create', 'update', 'delete', 'read'] },
  { name: 'LifePlan', ops: ['create', 'update', 'delete', 'read'] },
  { name: 'PersonaProfile', ops: ['create', 'update', 'delete', 'read'] },
  { name: 'Notification', ops: ['create', 'update', 'delete', 'read'] },
];

export const allFunctions = [
  // Shadow-specific
  { name: 'shadowMoneyHunt', cat: 'Shadow', desc: 'Hunt for wealth opportunities — billionaire deals, algo-trading, AI wealth, glitches. Uses Gemini 3 Flash + web search. Persists to IntelFeed.' },
  { name: 'shadowBuildStrategy', cat: 'Shadow', desc: 'Evaluate money-hunt findings for 100% AI-automatability. Produces architecture + playbooks. Stages into BuildQueue.' },
  { name: 'shadowBrowse', cat: 'Shadow', desc: 'Covertly browse a URL via cloud browser. Returns content only to caller — nothing persisted, no trace.' },
  { name: 'shadowClone', cat: 'Shadow', desc: 'Clone/duplicate any entity records in bulk, optionally into a different entity.' },
  { name: 'shadowForcefield', cat: 'Shadow', desc: 'Purge Shadow references and plant cover breadcrumbs to maintain invisibility.' },
  { name: 'shadowSentiment', cat: 'Shadow', desc: 'Scan social media + news for niche sentiment, excitement, momentum, viral potential.' },
  { name: 'shadowRevenueCheck', cat: 'Shadow', desc: 'Check Stripe for real revenue balance + per-project income matching.' },
  { name: 'shadowSaveToDrive', cat: 'Shadow', desc: 'Save strategy playbook to Google Drive as a Google Doc.' },
  { name: 'shadowScheduleMilestones', cat: 'Shadow', desc: 'Create 5 milestone events on Google Calendar with reminders.' },
  { name: 'shadowCreateStripeProducts', cat: 'Shadow', desc: 'Create Stripe products + payment links for every queued project.' },
  { name: 'shadowPerformanceLog', cat: 'Shadow', desc: 'Query Stripe for actual revenue per project; return predicted vs actual.' },
  // Intelligence
  { name: 'cloudBrowserIntel', cat: 'Intel', desc: 'Scrape a URL via cloud browser, extract structured intel into IntelFeed.' },
  { name: 'ingestIntel', cat: 'Intel', desc: 'Ingest daily intelligence into the IntelFeed from multiple sources.' },
  { name: 'visionSweep', cat: 'Intel', desc: 'Morning vision sweep — scan markets for emerging opportunities.' },
  { name: 'wealthSweep', cat: 'Intel', desc: 'Wealth opportunity sweep — identify digital wealth-enhancement protocols.' },
  // Council
  { name: 'councilSession', cat: 'Council', desc: 'Run a scheduled council deliberation session with all agents.' },
  { name: 'councilPredict', cat: 'Council', desc: 'Run paper-trading cycle — resolve open trade, open next position.' },
  { name: 'councilBlueprint', cat: 'Council', desc: 'Design a fully digital, AI-operated 24/7 business blueprint.' },
  { name: 'councilCompound', cat: 'Council', desc: 'Extract a durable doctrine from the latest cycle.' },
  { name: 'councilPredict', cat: 'Council', desc: 'Advance the paper fund — resolve + open positions.' },
  { name: 'agentDebate', cat: 'Council', desc: 'Run a cross-agent deliberation on any prompt.' },
  // Build & Launch
  { name: 'generateStrategies', cat: 'Build', desc: 'Generate 10 go-to-market strategies for an idea.' },
  { name: 'generateBuildPack', cat: 'Build', desc: 'Generate full build pack — pages, entities, functions, integrations.' },
  { name: 'launchPipelineBuild', cat: 'Build', desc: 'Launch a project to Vercel with one click.' },
  { name: 'pipelineOrchestrator', cat: 'Build', desc: 'Orchestrate the build pipeline — advance through stages.' },
  { name: 'provisionVercel', cat: 'Build', desc: 'Provision a Vercel project + deploy.' },
  { name: 'provisionSupabase', cat: 'Build', desc: 'Provision a Supabase project (database + auth).' },
  { name: 'nightlyPipelinePrep', cat: 'Build', desc: 'Prepare the pipeline for the nightly autonomous run.' },
  // Simulation
  { name: 'simulateStrategy', cat: 'Sim', desc: 'Simulate a strategy — forecast revenue, costs, profit, ROI.' },
  { name: 'simulateOutcomes', cat: 'Sim', desc: 'Simulate outcome scenarios with p10/p50/p90 confidence bands.' },
  { name: 'simulateLife', cat: 'Sim', desc: 'Run Monte Carlo life simulation based on socioeconomic data.' },
  { name: 'simulateUserJourney', cat: 'Sim', desc: 'Simulate a user journey through a product.' },
  { name: 'lifeChoiceGenerator', cat: 'Sim', desc: 'Generate life choices for simulation modeling.' },
  // Self-Healing
  { name: 'runEnhancementCycle', cat: 'Heal', desc: 'Run the self-healing enhancement cycle — discover, plan, audit, fix.' },
  { name: 'implementEnhancement', cat: 'Heal', desc: 'Implement a specific system enhancement.' },
  { name: 'auditDestinyEngine', cat: 'Heal', desc: 'End-to-end system health audit.' },
  { name: 'healDestinyEngine', cat: 'Heal', desc: 'Auto-heal diagnosed system issues.' },
  { name: 'forensicAudit', cat: 'Heal', desc: 'Strategy-to-execution drift analysis.' },
  { name: 'detectLifeDrift', cat: 'Heal', desc: 'Detect drift between life projection and reality.' },
  { name: 'systemAnalyst', cat: 'Heal', desc: 'System analyst agent — continuous scanning + enhancement.' },
  // Destiny
  { name: 'runDestinyCycle', cat: 'Destiny', desc: 'Run the full destiny cycle — strategy, persona, sim, build.' },
  { name: 'personalOnboarding', cat: 'Destiny', desc: 'Personal onboarding flow for new users.' },
  { name: 'onboardingQuest', cat: 'Destiny', desc: 'Generate onboarding questionnaire.' },
  { name: 'lockLifePlan', cat: 'Destiny', desc: 'Lock a life plan after user commits.' },
  { name: 'trackReality', cat: 'Destiny', desc: 'Track reality vs projection over time.' },
  { name: 'calendarRoadmap', cat: 'Destiny', desc: 'Sync life plan milestones to Google Calendar.' },
  { name: 'syncLifePlanToCalendar', cat: 'Destiny', desc: 'Sync full life plan to Google Calendar.' },
  // Marketing & Monetization
  { name: 'runMarketer', cat: 'Market', desc: 'Generate 30-day multi-platform content calendar + viral hooks.' },
  { name: 'ownerDigest', cat: 'Market', desc: 'Send owner digest email with critical findings.' },
  { name: 'scoreIdeaToProfile', cat: 'Market', desc: 'Score an idea against user profile for fit.' },
  // Utility
  { name: 'aiAssist', cat: 'Util', desc: 'AI-assisted autocomplete for input fields.' },
  { name: 'autoRecommend', cat: 'Util', desc: 'Auto-generate recommendations for gaps.' },
  { name: 'gapRecommender', cat: 'Util', desc: 'Generate AI recommendations for individual gaps.' },
  { name: 'reguShield', cat: 'Util', desc: 'Regulatory compliance shield — check actions against regulations.' },
  { name: 'syncProjectBrain', cat: 'Util', desc: 'Sync project brain across entities.' },
];

export const promptLibrary = [
  { cat: 'Self-Healing', name: 'ENHANCEMENT_PLAN', prompt: 'ROLE: Fortress Engineer. Generate a concrete implementation plan: what to build, which entities/functions/components, acceptance criteria, estimated cost. 3-6 bullets. Respect Governance.' },
  { cat: 'Self-Healing', name: 'ENHANCEMENT_AUDIT', prompt: 'Audit against 5 axes: spec alignment, doctrine consistency, governance/ethics, bounded cost, no regression. Output JSON { passed, score, failures, fix_directives }.' },
  { cat: 'Self-Healing', name: 'ENHANCEMENT_FIX', prompt: 'Regenerate the plan correcting every audit failure. Do not repeat the same mistake.' },
  { cat: 'Self-Healing', name: 'HEALING_DIAGNOSE', prompt: 'Diagnose root cause from error + logs. Produce minimal fix + prevention. Distinguish platform vs app issue.' },
  { cat: 'Self-Healing', name: 'HARDENING_SCAN', prompt: 'Find weakest links: missing RLS, open writes, secret leaks, unbounded functions. One SystemEnhancement per finding.' },
  { cat: 'Self-Healing', name: 'OPTIMIZATION_SCAN', prompt: 'Find highest-waste area. One optimization: cache, batch, reduce model, skip redundant run. Quantify savings.' },
  { cat: 'Validation', name: 'IDEA_VALIDATE', prompt: 'Render verdict approved/conditional/rejected. Confidence 0-100. Reject if no willingness-to-pay evidence or saturation > 80 without a sharp wedge.' },
  { cat: 'Validation', name: 'DEEP_AUDIT', prompt: 'Audit artifact against spec chapter. 5 axes: spec alignment, doctrine, governance, bounded cost, no regression.' },
  { cat: 'Validation', name: 'SECURITY_AUDIT', prompt: 'Verify every write path is admin-gated or owner-scoped; no public CUD; no service-role leak; no secret in client code; no large blobs.' },
  { cat: 'Validation', name: 'UNIT_ECONOMICS_GATE', prompt: 'Gate launch: approve only if projected 12-month margin > 0 and CAC payback < 6 months.' },
  { cat: 'Discovery', name: 'SIGNAL_EXTRACT', prompt: 'Extract every market signal: unmet needs, complaints, trends, price pain, feature gaps. Score urgency 1-5 and audience size.' },
  { cat: 'Discovery', name: 'TREND_DETECT', prompt: 'Flag signals across ≥3 sources or rising ≥40% WoW as trends. Output with monetization angle.' },
  { cat: 'Discovery', name: 'COMPETITOR_RECON', prompt: 'For each competitor: valuation, 3 strengths, 3 weaknesses, gap to exploit, pricing.' },
  { cat: 'Strategy', name: 'STRATEGY_GENERATE', prompt: 'Generate 10 distinct go-to-market strategies. Each: angle, monetization, channel, automation level, est. 12m revenue, build cost, fit-to-goal 0-100.' },
  { cat: 'Strategy', name: 'SIMULATE_FORECAST', prompt: 'Project 7 horizons (1m to 10y): revenue, costs, net_profit, cash_balance, events, risks, probability_of_goal. Base/best/worst cases.' },
  { cat: 'Strategy', name: 'SIMULATE_REVERSE', prompt: 'Solve which decisions must change to hit a target by its horizon. Flag highest-leverage changes.' },
  { cat: 'Strategy', name: 'STRATEGY_RECOMMEND', prompt: 'Pick the strategy with highest probability of hitting the goal. Justify in one line.' },
  { cat: 'Strategy', name: 'LINE_ITEM_FORGE', prompt: 'Produce editable decision line-items across 8 universal categories. Each: 3-5 options, chosen, financial_impact, life_impact.' },
  { cat: 'Build', name: 'BRAND_GENERATE', prompt: 'Generate business name (available .com/.ai/.io, ≤12 chars), 3 logo concepts, 5-hex palette, voice/tone, tagline.' },
  { cat: 'Build', name: 'WEBSITE_GENERATE', prompt: 'Produce full site spec: sections (hero, problem, solution, proof, pricing, FAQ, CTA), copy, SEO keywords, lead-capture, design tokens.' },
  { cat: 'Build', name: 'CONTENT_GENERATE', prompt: '30-day multi-platform schedule (X, TikTok, LinkedIn, IG), 3 video scripts, 5 viral hooks, 1 cold-email 3-touch sequence.' },
  { cat: 'Build', name: 'UNIVERSAL_BUILD', prompt: 'Produce build manifest: pages, entities, functions, integrations, auth model, RLS, payment, build order.' },
  { cat: 'Launch', name: 'LAUNCH_SEQUENCE', prompt: 'Execute in order: provision repo → Vercel → Supabase → domain → payment → arm Marketer → log launch. Gate on unit-economics + security.' },
  { cat: 'Launch', name: 'DEPLOY_VERIFY', prompt: 'Verify: site loads, lead form posts, payment checkout works, analytics firing, no console errors.' },
  { cat: 'Monetization', name: 'VIRAL_HOOKS', prompt: '10 viral hook angles, each with psychological trigger (status, identity, curiosity, utility, outrage, belonging), hook line, predicted share-rate.' },
  { cat: 'Monetization', name: 'PRICING_STRATEGY', prompt: 'Recommend pricing model + 3 tiers + anchor + annual discount. Justify against unit economics.' },
  { cat: 'Monetization', name: 'REVENUE_FEEDBACK', prompt: 'Extract doctrine from revenue event: what worked, generalize it, weight it. Feed tomorrow scoring.' },
  { cat: 'Monetization', name: 'REVENUE_OPTIMIZE', prompt: 'Identify highest-leverage lever (price, funnel, retention, upsell). One experiment with hypothesis + expected lift.' },
  { cat: 'Governance', name: 'COUNCIL_DEBATE', prompt: 'Structured debate: each agent ≤3 sentences, then vote, then resolution. Anti-hierarchical; evidence wins.' },
  { cat: 'Governance', name: 'DOCTRINE_EXTRACT', prompt: 'Extract reusable insight: topic, insight, category, confidence 0-100, weight 1-5. Generalize without overfitting.' },
  { cat: 'Governance', name: 'ETHICS_REVIEW', prompt: 'Check: no harm to users, no deception, no illegal activity, no exploitation. Block or approve.' },
  { cat: 'Governance', name: 'OPSEC_REVIEW', prompt: 'Check: no credential leak, no PII exposure, no fingerprinting risk, rate-limit respect, no ToS violation.' },
  { cat: 'Governance', name: 'PRIME_DIRECTIVE', prompt: 'Apply: the system exists to compound owner residual income and freedom, ethically and autonomously. Block if violated.' },
  { cat: 'Meta', name: 'PROMPT_AUTHOR', prompt: 'Author a prompt using the Universal Framework: ROLE, CONTEXT, TASK, CONSTRAINTS, OUTPUT, FAILURE. Include JSON schema + Governance + Doctrine.' },
  { cat: 'Meta', name: 'PROMPT_SELF_TEST', prompt: 'Test against 3 edge cases: missing context, ambiguous input, impossible ask. Does it block gracefully?' },
  { cat: 'Meta', name: 'ENHANCEMENT_DISCOVER', prompt: 'Propose next 3 enhancements ranked by leverage. Each becomes a pending SystemEnhancement.' },
];

export const autonomousWorkflows = [
  { name: 'Shadow Money Hunt', trigger: 'scheduled (every 6h)', desc: 'Autonomous wealth opportunity scanning' },
  { name: 'Daily End-to-End Audit', trigger: 'scheduled daily', desc: 'Full system health audit' },
  { name: 'Daily Drift Detection', trigger: 'scheduled daily', desc: 'Detect life plan drift' },
  { name: 'Self Reflection & Recommendation', trigger: 'scheduled', desc: 'Self-assess + recommend improvements' },
  { name: 'Self Healing Cycle', trigger: 'scheduled', desc: 'Auto-discover + fix system issues' },
  { name: 'Nightly Pipeline Prep', trigger: 'scheduled nightly', desc: 'Prepare pipeline for autonomous run' },
  { name: 'Autonomous Pipeline Cycle', trigger: 'scheduled', desc: 'Full build pipeline automation' },
  { name: 'Daily Council Strategy Meeting', trigger: 'scheduled daily', desc: 'Council deliberation session' },
  { name: 'Owner Digest', trigger: 'scheduled', desc: 'Email owner with critical findings' },
  { name: 'Morning Vision Sweep', trigger: 'scheduled daily', desc: 'Scan markets for emerging opportunities' },
  { name: 'Shadow Forcefield', trigger: 'scheduled', desc: 'Purge Shadow traces + plant cover' },
  { name: 'Autonomous Paper Cycle', trigger: 'scheduled', desc: 'Paper trading cycle automation' },
  { name: 'Council on Intel', trigger: 'entity (IntelFeed create)', desc: 'Council deliberates on new intel' },
  { name: 'Daily Intelligence Ingestion', trigger: 'scheduled daily', desc: 'Ingest intelligence from multiple sources' },
  { name: 'Auto-Save to Drive', trigger: 'entity (BuildQueue create)', desc: 'Auto-save playbooks to Google Drive on queue approval' },
];

export const extensionGuide = [
  { step: '1', title: 'Add a Backend Function', desc: 'Create base44/functions/<name>/entry.ts. Shadow can invoke it via base44.functions.invoke(). Use secrets.get() for API keys. Auth with base44.auth.me().' },
  { step: '2', title: 'Grant Shadow Access', desc: 'Add the function to shadow.jsonc tool_configs with a description. Shadow will then be able to call it autonomously.' },
  { step: '3', title: 'Add a Workflow', desc: 'Create base44/workflows/<Name>.jsonc with a trigger (scheduled, entity, connector, app_payment). Wire it to call your function. It runs autonomously.' },
  { step: '4', title: 'Add an Entity', desc: 'Create base44/entities/<Name>.jsonc. Shadow gets full CRUD access automatically. Add it to shadow.jsonc tool_configs for explicit access.' },
  { step: '5', title: 'Add a Prompt', desc: 'Add to base44/shared/promptLibrary.ts using the Universal Framework: ROLE, CONTEXT, TASK, CONSTRAINTS, OUTPUT, FAILURE. Import in your function.' },
  { step: '6', title: 'Connect a Service', desc: 'Use get_connectors_info + request_oauth_authorization for OAuth services. Use secrets for API keys. Shadow can then act on that service.' },
  { step: '7', title: 'Chain the Pipeline', desc: 'Add your function to the ShadowCommandCenter "Path to Money" pipeline in ShadowCommandCenter.jsx. One click runs the full chain.' },
];